### ISSUE TITLE
cannot unmarshal servicePort from variable

### ISSUE THREAD

**Issue by kamsz** [ContainX/depcon#42]
Hi,

I've set my portMappings as below:

```
          portMappings:
            - containerPort: 80
              servicePort: ${SERVICE_PORT}
              protocol: tcp
```

But I'm unable to create an application with servicePort as a variable due to:

```
2017-02-27 08:43:01 ERROR [depcon]: error unmarshaling JSON: json: cannot unmarshal string into Go value of type int
```

Is there any way to convert this value to an integer?
